import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import api from "../../api/axios";
import EmptyState from "../../components/ui/EmptyState";
import Loading from "../../components/ui/Loading";
import PageHeader from "../../components/ui/PageHeader";
import Pagination from "../../components/ui/Pagination";
import StatusBadge from "../../components/ui/StatusBadge";
import { getErrorMessage, money, showTimeLabel } from "../../utils/formatters";

const TicketsPage=({scope="customer"})=>{const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[pages,setPages]=useState(1),[status,setStatus]=useState("");const endpoint=scope==="customer"?"/tickets/my-tickets":"/tickets/admin/all";const load=async()=>{setLoading(true);try{const{data}=await api.get(endpoint,{params:{page,limit:10,status:status||undefined}});setItems(data.tickets||[]);setPages(data.pages||1);}catch(e){toast.error(getErrorMessage(e,"Failed to load tickets"));}finally{setLoading(false);}};useEffect(()=>{load();},[page,status]);const cancel=async(id)=>{try{const{data}=await api.patch(`/tickets/admin/${id}/cancel`);toast.success(data.message||"Ticket cancelled");load();}catch(e){toast.error(getErrorMessage(e,"Cancel failed"));}};const markUsed=async(id)=>{try{const{data}=await api.patch(`/tickets/${id}/mark-used`);toast.success(data.message||"Marked used");load();}catch(e){toast.error(getErrorMessage(e,"Mark used failed"));}};return <><PageHeader title={scope==="customer"?"My Tickets":"Ticket Management"} subtitle="View, verify, download and email tickets."/><div className="mb-5 max-w-xs"><select className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3" value={status} onChange={e=>{setPage(1);setStatus(e.target.value);}}><option value="">All statuses</option>{["active","used","cancelled"].map(x=><option key={x}>{x}</option>)}</select></div>{loading?<Loading/>:items.length===0?<EmptyState/>:<div className="overflow-hidden rounded-3xl border border-white/10"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-white/[0.04] text-slate-400"><tr><th className="p-4">Ticket</th><th>Customer</th><th>Movie</th><th>Showtime</th><th>Seats</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody className="divide-y divide-white/10">{items.map(t=><tr key={t._id}><td className="p-4 font-bold">{t.ticketNumber}</td><td>{t.customer?.name||"Me"}</td><td>{t.movie?.title}</td><td>{showTimeLabel(t.showtime)}</td><td>{t.seats?.map(s=>s.seatCode).join(", ")}</td><td>{money(t.totalAmount)}</td><td><StatusBadge value={t.ticketStatus}/></td><td><div className="flex flex-wrap gap-2"><Link to={`/tickets/${t._id}`} className="rounded-xl border border-white/10 px-3 py-2">View</Link>{scope!=="customer"&&t.ticketStatus==="active"&&<button onClick={()=>markUsed(t._id)} className="rounded-xl border border-emerald-500/30 px-3 py-2 text-emerald-200">Mark used</button>}{scope!=="customer"&&t.ticketStatus!=="cancelled"&&<button onClick={()=>cancel(t._id)} className="rounded-xl border border-red-500/30 px-3 py-2 text-red-200">Cancel</button>}</div></td></tr>)}</tbody></table></div>}<Pagination page={page} pages={pages} onPageChange={setPage}/></>};export default TicketsPage;
