import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { Download, Mail } from "lucide-react";
import api from "../../api/axios";
import Loading from "../../components/ui/Loading";
import PageHeader from "../../components/ui/PageHeader";
import StatusBadge from "../../components/ui/StatusBadge";
import { getErrorMessage, money, showTimeLabel } from "../../utils/formatters";

const TicketDetailPage=({byBooking=false})=>{const{id,bookingId}=useParams();const[ticket,setTicket]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);try{const{data}=await api.get(byBooking?`/tickets/booking/${bookingId}`:`/tickets/${id}`);setTicket(data.ticket);}catch(e){setError(getErrorMessage(e,"Failed to load ticket"));}finally{setLoading(false);}};useEffect(()=>{load();},[id,bookingId]);const download=async()=>{try{const res=await api.get(`/tickets/${ticket._id}/download`,{responseType:"blob"});const url=URL.createObjectURL(new Blob([res.data],{type:"application/pdf"}));const a=document.createElement("a");a.href=url;a.download=`ticket-${ticket.ticketNumber}.pdf`;a.click();URL.revokeObjectURL(url);}catch(e){toast.error(getErrorMessage(e,"Download failed"));}};const email=async()=>{try{const{data}=await api.post(`/tickets/${ticket._id}/email`);toast.success(data.message||"Email sent");}catch(e){toast.error(getErrorMessage(e,"Email failed"));}};if(loading)return <Loading/>; if(error)return <div className="text-red-200">{error}</div>;return <><PageHeader title="Ticket Details" subtitle="Download or email the ticket PDF." action={<div className="flex gap-2"><button onClick={download} className="rounded-2xl bg-red-600 px-5 py-3 font-bold"><Download className="mr-2 inline h-5 w-5"/>Download</button><button onClick={email} className="rounded-2xl border border-white/10 px-5 py-3 font-bold"><Mail className="mr-2 inline h-5 w-5"/>Email</button></div>}/><div className="mx-auto max-w-3xl rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm text-slate-400">Ticket Number</p><h2 className="text-3xl font-black">{ticket.ticketNumber}</h2></div><StatusBadge value={ticket.ticketStatus}/></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Movie" value={ticket.movie?.title}/><Info label="Customer" value={ticket.customer?.name}/><Info label="Hall" value={ticket.hall?.name}/><Info label="Showtime" value={showTimeLabel(ticket.showtime)}/><Info label="Seats" value={ticket.seats?.map(s=>s.seatCode).join(", ")}/><Info label="Total" value={money(ticket.totalAmount)}/><Info label="Booking" value={ticket.booking?.bookingReference}/><Info label="Payment" value={ticket.paymentStatus}/></div><div className="mt-6 rounded-2xl border border-white/10 bg-slate-950 p-4"><p className="mb-2 text-sm text-slate-400">QR Data</p><code className="break-all text-xs text-slate-300">{ticket.qrCodeData}</code></div><Link to="/dashboard" className="mt-5 inline-block text-sm text-red-300">Back to dashboard</Link></div></>};
const Info=({label,value})=><div className="rounded-2xl border border-white/10 bg-slate-950/70 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-bold text-white">{value||"-"}</p></div>;
export default TicketDetailPage;
