import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { CheckCircle2, Loader2, XCircle } from "lucide-react";
import api from "../../api/axios";
import Loading from "../../components/ui/Loading";
import StatusBadge from "../../components/ui/StatusBadge";
import { getErrorMessage, money, showTimeLabel } from "../../utils/formatters";

const PaymentPage = () => {
  const { bookingId }=useParams(); const navigate=useNavigate(); const [booking,setBooking]=useState(null); const [payment,setPayment]=useState(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=async()=>{setLoading(true); setError(""); try{const [{data:bookingData},{data:payData}]=await Promise.all([api.get(`/bookings/${bookingId}`),api.post("/payments/create-payment-intent",{bookingId})]); setBooking(bookingData.booking); setPayment(payData.payment);}catch(err){setError(getErrorMessage(err,"Failed to prepare payment"));}finally{setLoading(false);}};
  useEffect(()=>{load();},[bookingId]);
  const confirm=async()=>{setBusy(true); try{const {data}=await api.post("/payments/demo-confirm",{bookingId,demoPaymentMethod:"pm_card_visa"}); toast.success(data.message||"Payment confirmed"); navigate(`/tickets/${data.ticket._id}`,{replace:true});}catch(err){toast.error(getErrorMessage(err,"Payment failed"));}finally{setBusy(false);}};
  const fail=async()=>{setBusy(true); try{const {data}=await api.post("/payments/demo-fail",{bookingId}); toast.error(data.message||"Payment failed and seats released"); navigate("/customer/bookings",{replace:true});}catch(err){toast.error(getErrorMessage(err,"Failed to mark payment failed"));}finally{setBusy(false);}};
  if(loading)return <div className="min-h-screen bg-slate-950"><Loading label="Preparing payment..."/></div>; if(error)return <main className="min-h-screen bg-slate-950 p-8 text-white"><div className="mx-auto max-w-xl rounded-3xl border border-red-500/30 bg-red-500/10 p-6 text-red-200">{error}</div></main>;
  return <main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-2xl rounded-3xl border border-white/10 bg-white/[0.04] p-6 shadow-2xl"><h1 className="text-3xl font-black">Complete payment</h1><p className="mt-2 text-slate-400">Demo Stripe flow for your reserved seats.</p><div className="mt-6 space-y-3 rounded-3xl border border-white/10 bg-slate-950/60 p-5"><div className="flex justify-between"><span className="text-slate-400">Reference</span><b>{booking?.bookingReference}</b></div><div className="flex justify-between"><span className="text-slate-400">Movie</span><b>{booking?.movie?.title}</b></div><div className="flex justify-between"><span className="text-slate-400">Showtime</span><b>{showTimeLabel(booking?.showtime)}</b></div><div className="flex justify-between"><span className="text-slate-400">Seats</span><b>{booking?.seats?.map((s)=>s.seatCode).join(", ")}</b></div><div className="flex justify-between"><span className="text-slate-400">Status</span><StatusBadge value={booking?.bookingStatus}/></div><div className="border-t border-white/10 pt-3 flex justify-between text-xl"><span>Total</span><b className="text-red-200">{money(booking?.totalAmount)}</b></div></div><div className="mt-5 rounded-2xl border border-blue-500/20 bg-blue-500/10 p-4 text-sm text-blue-100">PaymentIntent: {payment?.paymentIntentId || "created"}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={busy} onClick={confirm} className="flex items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-5 py-3 font-bold hover:bg-emerald-700 disabled:opacity-50">{busy?<Loader2 className="h-5 w-5 animate-spin"/>:<CheckCircle2 className="h-5 w-5"/>}Demo Pay Success</button><button disabled={busy} onClick={fail} className="flex items-center justify-center gap-2 rounded-2xl border border-red-500/30 px-5 py-3 font-bold text-red-200 hover:bg-red-500/10 disabled:opacity-50"><XCircle className="h-5 w-5"/>Demo Pay Fail</button></div><Link to="/customer/bookings" className="mt-5 block text-center text-sm text-slate-400 hover:text-white">Back to bookings</Link></div></main>;
};
export default PaymentPage;
