import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import api from "../../api/axios";
import Card from "../../components/ui/Card";
import Loading from "../../components/ui/Loading";
import PageHeader from "../../components/ui/PageHeader";
import StatusBadge from "../../components/ui/StatusBadge";
import { getErrorMessage, money } from "../../utils/formatters";

const AdminReportsPage=()=>{const[data,setData]=useState({rev:null,book:null,movies:null}),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const[rev,book,movies]=await Promise.all([api.get("/dashboard/admin/revenue-report"),api.get("/dashboard/admin/booking-report"),api.get("/dashboard/admin/movie-performance")]);setData({rev:rev.data,book:book.data,movies:movies.data});}catch(e){toast.error(getErrorMessage(e,"Failed to load reports"));}finally{setLoading(false);}};useEffect(()=>{load();},[]);const cleanup=async()=>{try{const{data}=await api.post("/maintenance/release-expired-reservations");toast.success(data.message||"Cleanup completed");}catch(e){toast.error(getErrorMessage(e,"Cleanup failed"));}};if(loading)return <Loading/>;return <><PageHeader title="Reports & Maintenance" subtitle="Revenue, bookings, movie performance, and reservation cleanup." action={<button onClick={cleanup} className="rounded-2xl bg-red-600 px-5 py-3 font-bold">Release expired reservations</button>}/><div className="grid gap-5 lg:grid-cols-3"><Card title="Revenue" value={money(data.rev?.summary?.totalRevenue)} subtitle={`${data.rev?.summary?.totalBookings||0} paid bookings`}/><Card title="Bookings" value={data.book?.summary?.totalBookings||0} subtitle="Selected period total"/><Card title="Movie records" value={data.movies?.count||data.movies?.movies?.length||0} subtitle="Performance items"/></div><section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h2 className="mb-4 text-xl font-black">Movie Performance</h2><div className="space-y-3">{(data.movies?.movies||data.movies?.performance||[]).map((m,i)=><div key={m._id||i} className="flex flex-col justify-between gap-2 rounded-2xl bg-slate-950/70 p-4 sm:flex-row"><div><p className="font-bold">{m.title||m.movieTitle}</p><p className="text-sm text-slate-400">Bookings: {m.totalBookings||m.bookingCount||0}</p></div><StatusBadge value={m.status||"active"}/></div>)}</div></section></>};export default AdminReportsPage;
